// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webistem.Data;

#nullable disable

namespace webistem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231129121731_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("webistem.Models.Abouts", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslık")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KısaAcıklama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("webistem.Models.Awards", b =>
                {
                    b.Property<int>("AwardsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AwardsId"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslık")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AwardsId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("webistem.Models.Education", b =>
                {
                    b.Property<int?>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("EducationId"), 1L, 1);

                    b.Property<string>("BolumunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EgtimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ortalama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversiteAdı")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("webistem.Models.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"), 1L, 1);

                    b.Property<string>("Açıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslık")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslık2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExperienceDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("KısaAcıklama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExperienceId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("webistem.Models.Interests", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslık")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("webistem.Models.Skılls", b =>
                {
                    b.Property<int>("SkıllsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkıllsId"), 1L, 1);

                    b.Property<string>("Baslık")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KısaAcıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İsAkısı")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkıllsId");

                    b.ToTable("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
